---
title: "Exercise"
author: "Gabriel Petrov"
date: "13/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(geojsonio)
library(leaflet)
library(dplyr)
library(magrittr)
library(RColorBrewer)
library(countrycode)
library(reshape2)
library(rworldmap)
library(htmlwidgets)
library(htmltools)
```

```{r}

setwd("~/Desktop/DAVIS/")

cait <- read.csv("~/Downloads/CAIT Country CO2 Emissions.csv",
                 skip = 1,
                 stringsAsFactors = FALSE) %>%
  rename(CO2 = 3) %>% # Shorten the name of the third column.
  filter(!(Country %in% c("European Union (28)", "World")) & Year == 2014) %>%
  mutate(Country = gsub("Micronesia",
                        "Federated States of Micronesia",
                        Country),
         Code = countrycode(Country, "country.name", "iso3c"))

spdf <- joinCountryData2Map(cait, nameJoinColumn = "Code")

# Remove Antarctica, see https://stackoverflow.com/questions/
# 46649696/how-do-i-make-a-world-map-in-r-without-antarctica
spdf <- subset(spdf, continent != "Antarctica")
#spdf <- spTransform(spdf, CRS = CRS("+proj=gall")) # Gall projection.
crp <- colorRampPalette(brewer.pal(9, "YlOrBr")) # Colours for maps.


# Cut points for turning numerical values into categories on the map.
breaks <- c(0, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000)

pal <- colorBin(crp(length(breaks)-1), domain = spdf$CO2, bins = breaks)


m <- leaflet(spdf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(CO2),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE))

labels <- sprintf(
  "<strong>%s</strong><br/>CO<sub>2</sub> levels: %g",
  spdf$Country, spdf$CO2
) %>% lapply(htmltools::HTML)


m <- leaflet(spdf, height = 512, width = 768) %>% # Multiples of 256
  setView(lng = 0, lat = 0, zoom = 1) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(CO2),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "black",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE), 
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) %>% 
  addLegend(pal = pal, 
            values = ~CO2, 
            opacity = 0.7, 
            title = "Metric Tons of CO<sub>2</sub>",
            position = "bottomleft")


title <- tags$div(HTML("CO<sub>2</sub> Emissions around the Globe in 2014"))

m <- m %>% addControl(title, position = "topright")
m
```






From here down, everything is shit. And by shit, I mean my attempt at making it plot with gall. Don't worry about any of it, I doubt you'll be able to understand, I've spent 6 hours on this shit and I still don't get it.


```{r, eval = FALSE, include=FALSE}

# +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
spdf2 <- spTransform(spdf, CRS = CRS("+proj=gall"))


n <- leaflet(spdf2, options =
               leafletOptions(
                 crs=leafletCRS(crsClass="L.Proj.CRS", code="ESRI:54016",
                                proj4def= "+proj=gall +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs",
                                resolutions = 1.5^(25:15)
                                ))) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(CO2),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE), 
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))

n

n %>% addLegend(pal = pal, values = ~CO2, opacity = 0.7, title = NULL,
                position = "bottomright")
n



sp::proj4string(spdf2)

leaflet(spdf2, options =
               leafletOptions(
                 crs=leafletCRS(crsClass="L.Proj.CRS", code="ESRI:54016",
                                proj4def= "+proj=gall +ellps=WGS84",
                                resolutions = c(65536, 32768, 16384, 8192, 4096, 2048)
                                ))) %>%  addTiles()
  
  
addGraticule(sphere = TRUE, style= list(color= '#999', weight= 0.5, opacity= 1)) 

?leafletOptions

leaflet(options =
          leafletOptions(worldCopyJump = FALSE, maxZoom = 5,
               crs=leafletCRS(
                 crsClass="L.Proj.CRS", code='ESRI:53009',
                        proj4def= '+proj=moll +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs',
                        resolutions = c(65536, 32768, 16384, 8192, 4096, 2048,1024, 512, 256, 128)
                       ))) %>%
  addGraticule(style= list(color= '#999', weight= 0.5, opacity= 1)) %>%
  addGraticule(sphere = TRUE, style= list(color= '#777', weight= 1, opacity= 0.25))






minZoom = 0
maxZoom = 13
resolutions <- 0.42*(2^(maxZoom:minZoom))

epsg28992 <- leafletCRS(crsClass = 'L.Proj.CRS.TMS', code = 'EPSG:28992',
                       proj4def = '+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs',
                       resolutions = resolutions,
                       projectedBounds = c(-285401.92, 22598.08, 595401.9199999999, 903401.9199999999))

leaflet() %>% leaflet(options = leafletOptions(
                                  crs = epsg28992, 
                                  minZoom = minZoom, maxZoom = maxZoom)) %>%
  setView(5.092098, 52.093992, zoom = 4) %>%
  addTiles('http://geodata.nationaalgeoregister.nl/tms/1.0.0/brtachtergrondkaart/{z}/{x}/{y}.png', options = tileOptions(tms=TRUE))


'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
	attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
});
```




```{r}
library(tmap)
spdf2 <- spTransform(spdf, CRS = CRS("+proj=gall"))
data(World)
map <- tm_shape(World, projection ="gall") +
  tm_polygons(title = "Gall") 

leaflet(spdf2, options =
               leafletOptions(
                 crs=leafletCRS(crsClass="L.Proj.CRS", code="ESRI:54016",
                                proj4def= "+proj=gall +ellps=WGS84",
                                resolutions = c(65536, 32768, 16384, 8192, 4096, 2048)
                                ))) %>%  addTiles(map)
```

