---
title: "ggmap"
output: 
  html_document:
    toc: true
---

Sources: 
- https://www.sharpsightlabs.com/blog/mapping-seattle-crime/
- https://www.r-bloggers.com/how-to-plot-basic-maps-with-ggmap/



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggmap)
library(dplyr)
```

##Getting the map
```{r, eval = FALSE}
get_map("Tokyo") %>% ggmap()
get_map("Japan", zoom = 5) %>% ggmap()

# this is properly zoomed
get_map("Shinjuku", zoom = 16) %>% ggmap()
```

##Adding Data
```{r, eval=FALSE}
df.tokyo_locations <- tibble(location = c("Ueno, Tokyo, Japan",
                                          "Shibuya, Tokyo, Japan",
                                          "Shinjuku, Tokyo, Japan"))


# GEOCODE
geo.tokyo_locations <- geocode(df.tokyo_locations$location)


# COMBINE DATA
df.tokyo_locations <- cbind(df.tokyo_locations, geo.tokyo_locations)


# USE WITH GGPLOT
get_map("Tokyo", zoom = 11) %>% ggmap() +
  geom_point(data = df.tokyo_locations, aes(x = lon, y = lat), color = 'red', size = 3)
```


#Let's do something more advanced

##Seattle Crime:
Clear your environment

```{r, message=FALSE}
download.file("https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2015/01/seattle_crime_2010_to_2014_REDUCED.txt.zip", destfile="seattle_crime_2010_to_2014_REDUCED.txt.zip")

unzip("seattle_crime_2010_to_2014_REDUCED.txt.zip")

df.seattle_crime <- read.csv("seattle_crime_2010_to_2014_REDUCED.txt")

map.seattle_city <- qmap("seattle", zoom = 11, source="stamen", maptype="toner",darken = c(.3,"#BBBBBB"))

```


##Let's add Data
```{r, eval = FALSE}
map.seattle_city +
  geom_point(data=df.seattle_crime, aes(x=Longitude, y=Latitude), color="dark green", alpha=.01, size=1.1)
```

##Let's make it pretty

```{r}
map.seattle_city +
  stat_density2d(data=df.seattle_crime, aes(x=Longitude,
                                            y=Latitude,
                                            color=..density..,
                                            size=ifelse(..density..<=1,0,..density..),
                                            alpha=..density..),
                 geom="tile",contour=F) +
  scale_color_continuous(low="orange", high="red", guide = "none") +
  scale_size_continuous(range = c(0, 3), guide = "none") +
  scale_alpha(range = c(0,.5), guide="none") +
  ggtitle("Seattle Crime") +
  theme(plot.title = element_text(family="Trebuchet MS", size=36, face="bold", hjust=0, color="#777777"))
```

```{r, eval = FALSE}
qmap(location = "boston university", zoom = 14, source = "google")
qmap(location = "boston university", zoom = 14, source = "stamen")
```

